@baseUrl = http://localhost:3000/api/v1
@token = {{token}}

### 1) Ping inicial (endpoint actual en Nest)
GET {{baseUrl}}/
Accept: application/json

### 2) Ejemplo con auth bearer (deja @token en settings)
GET {{baseUrl}}/profile
Authorization: Bearer {{token}}
Accept: application/json

### 3) Plantilla CRUD para Products (ajusta rutas segun tu controller)
GET {{baseUrl}}/productos
Accept: application/json

###
GET {{baseUrl}}/productos/1006dcf1-d1e7-45be-9b61-80154b1ec40d
Accept: application/json

###
POST {{baseUrl}}/productos
Content-Type: application/json

{
  "name": "Mouse Logitech",
  "price": "39.99"
}

###
PATCH {{baseUrl}}/products/1
Content-Type: application/json

{
  "price": 34.99,
  "stock": 20
}

###
DELETE {{baseUrl}}/c068c397-eefc-4c51-9b2a-08b93300bab5
Accept: application/json
